version: 2
updates:
  - package-ecosystem: maven
    directory: "/" # Location of package manifests
    schedule:
      interval: daily
      time: "02:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[dependabot] "
    allow:
      - dependency-name: "horreum*"
    ignore:
      - dependency-name: "*"
      - dependency-exclude: "horreum*"
